
import LINKS from 'utils/constants/links';

const FOOTER_MENU_LINKS = [
  {
    HREF: LINKS.ADD_PROJECT.HREF,
    TITLE: LINKS.ADD_PROJECT.TITLE
  },
  {
    HREF: LINKS.ADD_SYSTEM.HREF,
    TITLE: LINKS.ADD_SYSTEM.TITLE
  },
  {
    HREF: LINKS.ADD_USER.HREF,
    TITLE: LINKS.ADD_USER.TITLE
  },
  {
    HREF: LINKS.ADD_SOW.HREF,
    TITLE: LINKS.ADD_SOW.TITLE
  },
  {
    HREF: LINKS.ADD_WORKFLOW_TEMPLATE.HREF,
    TITLE: LINKS.ADD_WORKFLOW_TEMPLATE.TITLE
  },
  {
    HREF: LINKS.ADD_PHASE_TEMPLATE.HREF,
    TITLE: LINKS.ADD_PHASE_TEMPLATE.TITLE
  }
]

export default FOOTER_MENU_LINKS