const SYSTEMS = [
  {
    id: "0001",
    name: "BCPF ECQ",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0002",
    name: "RF Sealer",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Custom",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0003",
    name: "abcdE",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Custom",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0004",
    name: "200L SUM",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0005",
    name: "Cytation 5 (#3)",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0006",
    name: "TSCD Welder",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0007",
    name: "LN2 Freezer",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0008",
    name: "Vox_Sys1",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0009",
    name: "Vox_Sys2",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0010",
    name: "Vox_Sys3",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0011",
    name: "Xuri (#1)",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0012",
    name: "Xuri (#2)",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0013",
    name: "Xuri (#3)",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
  {
    id: "0014",
    name: "Xuri (#4)",
    workflow: {
      id: "0001",
      name: "CEL3000 (v1.0)",
    },
    project: {
      id: "0001",
      name: "BCPF ECQ",
    },
    equipment: {
      category: "Commercial off the shelf",
      type: "Process",
      name: "Tube Sealer",
      number: "WAR-TUBS-027",
    },
    totalHours: 508,
    pv: 1,
    status: 0.9,
    effort: 0.9,
    ev: 0.89,
  },
];

export default SYSTEMS;
