const SET_CURRENT_USER = 'SET_CURRENT_USER'
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN'
const SET_PASSWORD_RESET_TOKEN = 'SET_PASSWORD_RESET_TOKEN'
const SET_LOADING_STATUS = 'SET_LOADING_STATUS'

const FETCH_USERS = 'FETCH_USERS'
const FETCH_PROJECTS = 'FETCH_PROJECTS'
const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS'
const FETCH_WORKFLOW_TEMPLATES = 'FETCH_WORKFLOW_TEMPLATES'
const FETCH_EVENTS = 'FETCH_EVENTS'
const FETCH_LATEST_EVENTS = 'FETCH_LATEST_EVENTS'
const FETCH_DASHBOARDS = 'FETCH_DASHBOARDS'
const FETCH_REPORTS = 'FETCH_REPORTS'

export {
  SET_CURRENT_USER,
  SET_ACCESS_TOKEN,
  SET_REFRESH_TOKEN,
  SET_PASSWORD_RESET_TOKEN,
  SET_LOADING_STATUS,
  FETCH_USERS,
  FETCH_PROJECTS,
  FETCH_ORGANIZATIONS,
  FETCH_WORKFLOW_TEMPLATES,
  FETCH_EVENTS,
  FETCH_LATEST_EVENTS,
  FETCH_DASHBOARDS,
  FETCH_REPORTS
};
